Traceback (most recent call last):
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
from datetime import datetime
import pandas_datareader.data as web

df = web.DataReader(
    "AD",
    "av-daily",
    start=datetime(2008, 1, 1),
    end=datetime(2018, 2, 28),
    api_key=os.gehide-outputtenv("ALPHAVANTAGE_API_KEY"),
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_342243/3614967667.py[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m     [0mstart[0m[0;34m=[0m[0mdatetime[0m[0;34m([0m[0;36m2008[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m     [0mend[0m[0;34m=[0m[0mdatetime[0m[0;34m([0m[0;36m2018[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m28[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m     [0mapi_key[0m[0;34m=[0m[0mos[0m[0;34m.[0m[0mgehide[0m[0;34m-[0m[0moutputtenv[0m[0;34m([0m[0;34m"ALPHAVANTAGE_API_KEY"[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m )

[0;31mAttributeError[0m: module 'os' has no attribute 'gehide'
AttributeError: module 'os' has no attribute 'gehide'

